### ISSUE TITLE
Final Score Update

### ISSUE THREAD

**Issue by justincav15** [Rochester-Biomedical-DS/Hackathon-Summer-2020#8]
Hi,

On the page it says, "Competition runs through 11:59 PM EDT 12-August-2020." However, the final grade was only 25 seconds after this time. I submitted a prediction.csv after the time the scores were updated, but before the end of the day. I was wondering if you would please be able to update it again so that the leaderboard would reflect our most updated predictions. I apologize for the inconvenience as I am one to normally work right up until the deadline. Thank you.

![hackathon submission](https://user-images.githubusercontent.com/47338548/90093688-2fcb2a80-dcfa-11ea-89a7-f9d50402cdce.JPG)

**Comment by justincav15** [comment]
To clarify, I took "runs through" to be 11:59:59 as the last possible submission time, however the last update of prediction files was only 11:59:25 and I submitted between these two times.

**Comment by amcdavid** [comment]
No, there will not be any additional scoring done.   It would not be fair to other teams. It was scored as close to 11:59PM as possible.

**Comment by justincav15** [comment]
I understand. Would you at least be able to tell us the MSE for the prediction file we submitted? We did work hard on it and believe the one would score very well based on our training/testing splits. Thank you.

**Comment by amcdavid** [comment]
The test MSE is 27608.  No, that's not a typo, the file wasn't formatted correctly.  If you fix it and leave a message here I'll try scoring it again.

**Comment by justincav15** [comment]
Whoops, sorry about that. I re-uploaded a correctly formatted csv file. Thank you for doing this.

**Comment by amcdavid** [comment]
Closed in dd79615
